// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PriceSafari.Data;

#nullable disable

namespace PriceSafari.Migrations
{
    [DbContext(typeof(PriceSafariContext))]
    [Migration("20250214234124_RemAutoMatching")]
    partial class RemAutoMatching
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoOfrClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("GoogleIsRejected")
                        .HasColumnType("bit");

                    b.Property<bool>("GoogleIsScraped")
                        .HasColumnType("bit");

                    b.Property<string>("GoogleOfferUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GooglePricesCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsGoogle")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRejected")
                        .HasColumnType("bit");

                    b.Property<bool>("IsScraped")
                        .HasColumnType("bit");

                    b.Property<string>("OfferUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PricesCount")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("ProductIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("ProductIdsGoogle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("StoreNames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("StoreProfiles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CoOfrs");
                });

            modelBuilder.Entity("GlobalPriceReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<decimal>("CalculatedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CalculatedPriceWithDelivery")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OfferUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PriceSafariReportId")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceWithDelivery")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<int>("ScrapingProductId")
                        .HasColumnType("int");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReportId");

                    b.HasIndex("PriceSafariReportId");

                    b.HasIndex("ProductId");

                    b.HasIndex("RegionId");

                    b.ToTable("GlobalPriceReports");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PriceSafari.Models.AffiliateVerification", b =>
                {
                    b.Property<int>("AffiliateVerificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AffiliateVerificationId"));

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AffiliateVerificationId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("AffiliateVerification");
                });

            modelBuilder.Entity("PriceSafari.Models.CategoryClass", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.HasIndex("StoreId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("PriceSafari.Models.ClientProfile", b =>
                {
                    b.Property<int>("ClientProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientProfileId"));

                    b.Property<string>("CeneoProfileEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CeneoProfileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CeneoProfileProductCount")
                        .HasColumnType("int");

                    b.Property<string>("CeneoProfileTelephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CeneoProfileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmailSentCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastEmailSentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ScheduledMeetingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ClientProfileId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("ClientProfiles");
                });

            modelBuilder.Entity("PriceSafari.Models.CoOfrPriceHistoryClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AvailabilityNum")
                        .HasColumnType("int");

                    b.Property<int>("CoOfrClassId")
                        .HasColumnType("int");

                    b.Property<string>("ExportedName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GooglePosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GooglePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GooglePriceWithDelivery")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GoogleStoreName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsBidding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ShippingCostNum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StoreName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CoOfrClassId");

                    b.ToTable("CoOfrPriceHistories");
                });

            modelBuilder.Entity("PriceSafari.Models.DeviceStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("BaseScalEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("CenCrawEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GooCrawEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastCheck")
                        .HasColumnType("datetime2");

                    b.Property<bool>("UrlScalEnabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("DeviceStatuses");
                });

            modelBuilder.Entity("PriceSafari.Models.FlagsClass", b =>
                {
                    b.Property<int>("FlagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlagId"));

                    b.Property<string>("FlagColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StoreClassStoreId")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("FlagId");

                    b.HasIndex("StoreClassStoreId");

                    b.ToTable("Flags");
                });

            modelBuilder.Entity("PriceSafari.Models.GoogleScrapingProduct", b =>
                {
                    b.Property<int>("ScrapingProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScrapingProductId"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsScraped")
                        .HasColumnType("bit");

                    b.Property<int>("OffersCount")
                        .HasColumnType("int");

                    b.Property<int>("PriceSafariRaportId")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("ProductIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("ScrapingProductId");

                    b.HasIndex("RegionId");

                    b.ToTable("GoogleScrapingProducts");
                });

            modelBuilder.Entity("PriceSafari.Models.InvoiceClass", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("AppliedDiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AppliedDiscountPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OriginalProformaNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScrapesIncluded")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<int>("UrlsIncluded")
                        .HasColumnType("int");

                    b.HasKey("InvoiceId");

                    b.HasIndex("PlanId");

                    b.HasIndex("StoreId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("PriceSafari.Models.InvoiceCounter", b =>
                {
                    b.Property<int>("InvoiceCounterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceCounterId"));

                    b.Property<int>("LastInvoiceNumber")
                        .HasColumnType("int");

                    b.Property<int>("LastProformaNumber")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("InvoiceCounterId");

                    b.ToTable("InvoiceCounters");
                });

            modelBuilder.Entity("PriceSafari.Models.PlanClass", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<bool>("IsTestPlan")
                        .HasColumnType("bit");

                    b.Property<decimal>("NetPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductsToScrap")
                        .HasColumnType("int");

                    b.Property<int>("ScrapesPerInvoice")
                        .HasColumnType("int");

                    b.HasKey("PlanId");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("PriceSafari.Models.PriceData", b =>
                {
                    b.Property<int>("PriceDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriceDataId"));

                    b.Property<string>("OfferUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceWithDelivery")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<int>("ScrapingProductId")
                        .HasColumnType("int");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PriceDataId");

                    b.HasIndex("RegionId");

                    b.HasIndex("ScrapingProductId");

                    b.ToTable("PriceData");
                });

            modelBuilder.Entity("PriceSafari.Models.PriceHistoryClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AvailabilityNum")
                        .HasColumnType("int");

                    b.Property<string>("IsBidding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsGoogle")
                        .HasColumnType("bit");

                    b.Property<int?>("Position")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ScrapHistoryId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ShippingCostNum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ScrapHistoryId");

                    b.ToTable("PriceHistories");
                });

            modelBuilder.Entity("PriceSafari.Models.PriceSafariReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Prepared")
                        .HasColumnType("bit");

                    b.PrimitiveCollection<string>("ProductIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReadyDate")
                        .HasColumnType("datetime2");

                    b.PrimitiveCollection<string>("RegionIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("ReportId");

                    b.HasIndex("StoreId");

                    b.ToTable("PriceSafariReports");
                });

            modelBuilder.Entity("PriceSafari.Models.PriceSafariUserStore", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("UserId", "StoreId");

                    b.HasIndex("StoreId");

                    b.ToTable("UserStores");
                });

            modelBuilder.Entity("PriceSafari.Models.PriceValueClass", b =>
                {
                    b.Property<int>("PriceValueClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriceValueClassId"));

                    b.Property<decimal>("PriceStep")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SetPrice1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SetPrice2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SetSafariPrice1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SetSafariPrice2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<bool>("UsePriceDiff")
                        .HasColumnType("bit");

                    b.Property<bool>("UsePriceDiffSafari")
                        .HasColumnType("bit");

                    b.HasKey("PriceValueClassId");

                    b.HasIndex("StoreId");

                    b.ToTable("PriceValues");
                });

            modelBuilder.Entity("PriceSafari.Models.ProductClass", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CatalogNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ean")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EanGoogle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExportedNameCeneo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ExternalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("FoundOnCeneoDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("FoundOnGoogle")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FoundOnGoogleDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GoogleScrapingProductScrapingProductId")
                        .HasColumnType("int");

                    b.Property<string>("GoogleUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrlGoogle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRejected")
                        .HasColumnType("bit");

                    b.Property<bool>("IsScrapable")
                        .HasColumnType("bit");

                    b.Property<string>("MainUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MarginPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OfferUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OnGoogle")
                        .HasColumnType("bit");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductNameInStoreForGoogle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("GoogleScrapingProductScrapingProductId");

                    b.HasIndex("StoreId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("PriceSafari.Models.ProductFlag", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("FlagId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("ProductId", "FlagId");

                    b.HasIndex("FlagId");

                    b.ToTable("ProductFlags");
                });

            modelBuilder.Entity("PriceSafari.Models.ProductMap", b =>
                {
                    b.Property<int>("ProductMapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductMapId"));

                    b.Property<string>("CatalogNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ean")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExportedName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleEan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleExportedName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductMapId");

                    b.ToTable("ProductMaps");
                });

            modelBuilder.Entity("PriceSafari.Models.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegionId"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CurrencyValue")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegionId");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("PriceSafari.Models.SchedulePlan.DayDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("DayDetails");
                });

            modelBuilder.Entity("PriceSafari.Models.SchedulePlan.SchedulePlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FridayId")
                        .HasColumnType("int");

                    b.Property<int?>("MondayId")
                        .HasColumnType("int");

                    b.Property<int?>("SaturdayId")
                        .HasColumnType("int");

                    b.Property<int?>("SundayId")
                        .HasColumnType("int");

                    b.Property<int?>("ThursdayId")
                        .HasColumnType("int");

                    b.Property<int?>("TuesdayId")
                        .HasColumnType("int");

                    b.Property<int?>("WednesdayId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FridayId")
                        .IsUnique()
                        .HasFilter("[FridayId] IS NOT NULL");

                    b.HasIndex("MondayId")
                        .IsUnique()
                        .HasFilter("[MondayId] IS NOT NULL");

                    b.HasIndex("SaturdayId")
                        .IsUnique()
                        .HasFilter("[SaturdayId] IS NOT NULL");

                    b.HasIndex("SundayId")
                        .IsUnique()
                        .HasFilter("[SundayId] IS NOT NULL");

                    b.HasIndex("ThursdayId")
                        .IsUnique()
                        .HasFilter("[ThursdayId] IS NOT NULL");

                    b.HasIndex("TuesdayId")
                        .IsUnique()
                        .HasFilter("[TuesdayId] IS NOT NULL");

                    b.HasIndex("WednesdayId")
                        .IsUnique()
                        .HasFilter("[WednesdayId] IS NOT NULL");

                    b.ToTable("SchedulePlans");
                });

            modelBuilder.Entity("PriceSafari.Models.SchedulePlan.ScheduleTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("BaseEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("CeneoEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("DayDetailId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("GoogleEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastRunDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<bool>("UrlEnabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DayDetailId");

                    b.ToTable("ScheduleTasks");
                });

            modelBuilder.Entity("PriceSafari.Models.SchedulePlan.ScheduleTaskStore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ScheduleTaskId")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleTaskId");

                    b.HasIndex("StoreId");

                    b.ToTable("ScheduleTaskStores");
                });

            modelBuilder.Entity("PriceSafari.Models.ScheduledTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CeneoIsEnabled")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("CeneoScheduledTime")
                        .HasColumnType("time");

                    b.Property<bool>("GoogleIsEnabled")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("GoogleScheduledTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("ScheduledTime")
                        .HasColumnType("time");

                    b.Property<bool>("UrlIsEnabled")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("UrlScheduledTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("ScheduledTasks");
                });

            modelBuilder.Entity("PriceSafari.Models.ScrapHistoryClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("PriceCount")
                        .HasColumnType("int");

                    b.Property<int>("ProductCount")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("ScrapHistories");
                });

            modelBuilder.Entity("PriceSafari.Models.Settings", b =>
                {
                    b.Property<int>("SettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettingsId"));

                    b.Property<bool>("ControlXY")
                        .HasColumnType("bit");

                    b.Property<bool>("GetCeneoName")
                        .HasColumnType("bit");

                    b.Property<bool>("HeadLess")
                        .HasColumnType("bit");

                    b.Property<bool>("JavaScript")
                        .HasColumnType("bit");

                    b.Property<int>("Semophore")
                        .HasColumnType("int");

                    b.Property<int>("SemophoreGoogle")
                        .HasColumnType("int");

                    b.Property<bool>("Styles")
                        .HasColumnType("bit");

                    b.Property<bool>("VerificationRequired")
                        .HasColumnType("bit");

                    b.Property<int>("WarmUpTime")
                        .HasColumnType("int");

                    b.HasKey("SettingsId");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("PriceSafari.Models.StoreClass", b =>
                {
                    b.Property<int>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoreId"));

                    b.Property<decimal?>("DiscountPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GoogleMiG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlanId")
                        .HasColumnType("int");

                    b.Property<string>("ProductMapXmlUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductMapXmlUrlGoogle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductsToScrap")
                        .HasColumnType("int");

                    b.Property<int>("RemainingScrapes")
                        .HasColumnType("int");

                    b.Property<string>("StoreApiKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoreApiUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoreLogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoreProfile")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StoreId");

                    b.HasIndex("PlanId");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("PriceSafari.Models.TaskExecutionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TaskExecutionLogs");
                });

            modelBuilder.Entity("PriceSafari.Models.UserPaymentData", b =>
                {
                    b.Property<int>("PaymentDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentDataId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceAutoMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InvoiceAutoMailSend")
                        .HasColumnType("bit");

                    b.Property<string>("NIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PaymentDataId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPaymentDatas");
                });

            modelBuilder.Entity("PriceSafariUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("AccesToCreateSafari")
                        .HasColumnType("bit");

                    b.Property<bool>("AccesToSetMargin")
                        .HasColumnType("bit");

                    b.Property<bool>("AccesToViewMargin")
                        .HasColumnType("bit");

                    b.Property<bool>("AccesToViewSafari")
                        .HasColumnType("bit");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("CodePAR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMember")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("LoginCount")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PartnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartnerSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GlobalPriceReport", b =>
                {
                    b.HasOne("PriceSafari.Models.PriceSafariReport", "PriceSafariReport")
                        .WithMany()
                        .HasForeignKey("PriceSafariReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PriceSafari.Models.ProductClass", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PriceSafari.Models.Region", "Region")
                        .WithMany("GlobalPriceReports")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriceSafariReport");

                    b.Navigation("Product");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PriceSafariUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PriceSafariUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PriceSafariUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PriceSafariUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PriceSafari.Models.AffiliateVerification", b =>
                {
                    b.HasOne("PriceSafariUser", "PriceSafariUser")
                        .WithOne("AffiliateVerification")
                        .HasForeignKey("PriceSafari.Models.AffiliateVerification", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriceSafariUser");
                });

            modelBuilder.Entity("PriceSafari.Models.CategoryClass", b =>
                {
                    b.HasOne("PriceSafari.Models.StoreClass", "Store")
                        .WithMany("Categories")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("PriceSafari.Models.ClientProfile", b =>
                {
                    b.HasOne("PriceSafariUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("PriceSafari.Models.CoOfrPriceHistoryClass", b =>
                {
                    b.HasOne("CoOfrClass", "CoOfr")
                        .WithMany()
                        .HasForeignKey("CoOfrClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoOfr");
                });

            modelBuilder.Entity("PriceSafari.Models.FlagsClass", b =>
                {
                    b.HasOne("PriceSafari.Models.StoreClass", null)
                        .WithMany("Flags")
                        .HasForeignKey("StoreClassStoreId");
                });

            modelBuilder.Entity("PriceSafari.Models.GoogleScrapingProduct", b =>
                {
                    b.HasOne("PriceSafari.Models.Region", "Region")
                        .WithMany("GoogleScrapingProducts")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("PriceSafari.Models.InvoiceClass", b =>
                {
                    b.HasOne("PriceSafari.Models.PlanClass", "Plan")
                        .WithMany("Invoices")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PriceSafari.Models.StoreClass", "Store")
                        .WithMany("Invoices")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("PriceSafari.Models.PriceData", b =>
                {
                    b.HasOne("PriceSafari.Models.Region", null)
                        .WithMany("PriceData")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PriceSafari.Models.GoogleScrapingProduct", "ScrapingProduct")
                        .WithMany("PriceData")
                        .HasForeignKey("ScrapingProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScrapingProduct");
                });

            modelBuilder.Entity("PriceSafari.Models.PriceHistoryClass", b =>
                {
                    b.HasOne("PriceSafari.Models.ProductClass", "Product")
                        .WithMany("PriceHistories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PriceSafari.Models.ScrapHistoryClass", "ScrapHistory")
                        .WithMany("PriceHistories")
                        .HasForeignKey("ScrapHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ScrapHistory");
                });

            modelBuilder.Entity("PriceSafari.Models.PriceSafariReport", b =>
                {
                    b.HasOne("PriceSafari.Models.StoreClass", "Store")
                        .WithMany("PriceSafariReports")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("PriceSafari.Models.PriceSafariUserStore", b =>
                {
                    b.HasOne("PriceSafari.Models.StoreClass", "StoreClass")
                        .WithMany("UserStores")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PriceSafariUser", "PriceSafariUser")
                        .WithMany("UserStores")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriceSafariUser");

                    b.Navigation("StoreClass");
                });

            modelBuilder.Entity("PriceSafari.Models.PriceValueClass", b =>
                {
                    b.HasOne("PriceSafari.Models.StoreClass", "Store")
                        .WithMany("PriceValues")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("PriceSafari.Models.ProductClass", b =>
                {
                    b.HasOne("PriceSafari.Models.GoogleScrapingProduct", null)
                        .WithMany("Products")
                        .HasForeignKey("GoogleScrapingProductScrapingProductId");

                    b.HasOne("PriceSafari.Models.StoreClass", "Store")
                        .WithMany("Products")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("PriceSafari.Models.ProductFlag", b =>
                {
                    b.HasOne("PriceSafari.Models.FlagsClass", "Flag")
                        .WithMany("ProductFlags")
                        .HasForeignKey("FlagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PriceSafari.Models.ProductClass", "Product")
                        .WithMany("ProductFlags")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flag");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PriceSafari.Models.SchedulePlan.SchedulePlan", b =>
                {
                    b.HasOne("PriceSafari.Models.SchedulePlan.DayDetail", "Friday")
                        .WithOne()
                        .HasForeignKey("PriceSafari.Models.SchedulePlan.SchedulePlan", "FridayId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PriceSafari.Models.SchedulePlan.DayDetail", "Monday")
                        .WithOne()
                        .HasForeignKey("PriceSafari.Models.SchedulePlan.SchedulePlan", "MondayId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PriceSafari.Models.SchedulePlan.DayDetail", "Saturday")
                        .WithOne()
                        .HasForeignKey("PriceSafari.Models.SchedulePlan.SchedulePlan", "SaturdayId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PriceSafari.Models.SchedulePlan.DayDetail", "Sunday")
                        .WithOne()
                        .HasForeignKey("PriceSafari.Models.SchedulePlan.SchedulePlan", "SundayId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PriceSafari.Models.SchedulePlan.DayDetail", "Thursday")
                        .WithOne()
                        .HasForeignKey("PriceSafari.Models.SchedulePlan.SchedulePlan", "ThursdayId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PriceSafari.Models.SchedulePlan.DayDetail", "Tuesday")
                        .WithOne()
                        .HasForeignKey("PriceSafari.Models.SchedulePlan.SchedulePlan", "TuesdayId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PriceSafari.Models.SchedulePlan.DayDetail", "Wednesday")
                        .WithOne()
                        .HasForeignKey("PriceSafari.Models.SchedulePlan.SchedulePlan", "WednesdayId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Friday");

                    b.Navigation("Monday");

                    b.Navigation("Saturday");

                    b.Navigation("Sunday");

                    b.Navigation("Thursday");

                    b.Navigation("Tuesday");

                    b.Navigation("Wednesday");
                });

            modelBuilder.Entity("PriceSafari.Models.SchedulePlan.ScheduleTask", b =>
                {
                    b.HasOne("PriceSafari.Models.SchedulePlan.DayDetail", "DayDetail")
                        .WithMany("Tasks")
                        .HasForeignKey("DayDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DayDetail");
                });

            modelBuilder.Entity("PriceSafari.Models.SchedulePlan.ScheduleTaskStore", b =>
                {
                    b.HasOne("PriceSafari.Models.SchedulePlan.ScheduleTask", "ScheduleTask")
                        .WithMany("TaskStores")
                        .HasForeignKey("ScheduleTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PriceSafari.Models.StoreClass", "Store")
                        .WithMany("ScheduleTaskStores")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduleTask");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("PriceSafari.Models.ScrapHistoryClass", b =>
                {
                    b.HasOne("PriceSafari.Models.StoreClass", "Store")
                        .WithMany("ScrapHistories")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("PriceSafari.Models.StoreClass", b =>
                {
                    b.HasOne("PriceSafari.Models.PlanClass", "Plan")
                        .WithMany("Stores")
                        .HasForeignKey("PlanId");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("PriceSafari.Models.UserPaymentData", b =>
                {
                    b.HasOne("PriceSafariUser", "User")
                        .WithMany("UserPaymentDatas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PriceSafari.Models.FlagsClass", b =>
                {
                    b.Navigation("ProductFlags");
                });

            modelBuilder.Entity("PriceSafari.Models.GoogleScrapingProduct", b =>
                {
                    b.Navigation("PriceData");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("PriceSafari.Models.PlanClass", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Stores");
                });

            modelBuilder.Entity("PriceSafari.Models.ProductClass", b =>
                {
                    b.Navigation("PriceHistories");

                    b.Navigation("ProductFlags");
                });

            modelBuilder.Entity("PriceSafari.Models.Region", b =>
                {
                    b.Navigation("GlobalPriceReports");

                    b.Navigation("GoogleScrapingProducts");

                    b.Navigation("PriceData");
                });

            modelBuilder.Entity("PriceSafari.Models.SchedulePlan.DayDetail", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("PriceSafari.Models.SchedulePlan.ScheduleTask", b =>
                {
                    b.Navigation("TaskStores");
                });

            modelBuilder.Entity("PriceSafari.Models.ScrapHistoryClass", b =>
                {
                    b.Navigation("PriceHistories");
                });

            modelBuilder.Entity("PriceSafari.Models.StoreClass", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Flags");

                    b.Navigation("Invoices");

                    b.Navigation("PriceSafariReports");

                    b.Navigation("PriceValues");

                    b.Navigation("Products");

                    b.Navigation("ScheduleTaskStores");

                    b.Navigation("ScrapHistories");

                    b.Navigation("UserStores");
                });

            modelBuilder.Entity("PriceSafariUser", b =>
                {
                    b.Navigation("AffiliateVerification")
                        .IsRequired();

                    b.Navigation("UserPaymentDatas");

                    b.Navigation("UserStores");
                });
#pragma warning restore 612, 618
        }
    }
}
